curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop41/firecloud-workshop41@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop11/firecloud-workshop11@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop42/firecloud-workshop42@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop31/firecloud-workshop31@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop12/firecloud-workshop12@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop32/firecloud-workshop32@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop13/firecloud-workshop13@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop33/firecloud-workshop33@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop14/firecloud-workshop14@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop34/firecloud-workshop34@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop15/firecloud-workshop15@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop35/firecloud-workshop35@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop16/firecloud-workshop16@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop36/firecloud-workshop36@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop01/firecloud-workshop01@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop17/firecloud-workshop17@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop37/firecloud-workshop37@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop21/firecloud-workshop21@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop02/firecloud-workshop02@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop18/firecloud-workshop18@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop38/firecloud-workshop38@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop03/firecloud-workshop03@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop43/firecloud-workshop43@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop39/firecloud-workshop39@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop19/firecloud-workshop19@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop04/firecloud-workshop04@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop40/firecloud-workshop40@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop05/firecloud-workshop05@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop44/firecloud-workshop44@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop22/firecloud-workshop22@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop06/firecloud-workshop06@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop20/firecloud-workshop20@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop45/firecloud-workshop45@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop07/firecloud-workshop07@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop23/firecloud-workshop23@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop08/firecloud-workshop08@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop46/firecloud-workshop46@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop09/firecloud-workshop09@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop47/firecloud-workshop47@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop24/firecloud-workshop24@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop10/firecloud-workshop10@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop48/firecloud-workshop48@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop25/firecloud-workshop25@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop49/firecloud-workshop49@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop26/firecloud-workshop26@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop50/firecloud-workshop50@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop27/firecloud-workshop27@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop28/firecloud-workshop28@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop29/firecloud-workshop29@firecloud.org
curl -X PUT -H "Authorization: Bearer $TOKEN" https://local.broadinstitute.org:10443/api/admin/billing/firecloud-workshop30/firecloud-workshop30@firecloud.org