curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop41
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop11
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop42
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop31
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop12
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop32
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop13
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop33
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop14
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop34
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop15
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop35
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop16
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop36
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop01
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop17
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop37
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop21
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop02
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop18
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop38
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop03
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop43
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop39
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop19
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop04
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop40
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop05
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop44
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop22
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop06
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop20
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop45
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop07
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop23
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop08
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop46
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop09
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop47
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop24
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop10
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop48
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop25
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop49
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop26
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop50
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop27
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop28
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop29
curl -X PUT -H "Authorization: Bearer $TOKEN" https://rawls.dsde-dev.broadinstitute.org/api/admin/billing/firecloud-workshop30